-- ============================================================
--  Function: automatic updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Table: cocoUser
-- ============================================================
CREATE TABLE cocoUser (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        VARCHAR(255) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    email        VARCHAR(255) NOT NULL UNIQUE,
    image_url    TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_cocoUser_set_updated_at
BEFORE UPDATE ON cocoUser
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Table: project
-- ============================================================
CREATE TABLE project (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL UNIQUE,
    description  TEXT,
    logo_url     TEXT,

    status       VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_project_status
      CHECK (status IN ('ACTIVE', 'ARCHIVED', 'PAUSED'))
);

CREATE TRIGGER trg_project_set_updated_at
BEFORE UPDATE ON project
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Table: role
-- ============================================================
CREATE TABLE role (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name  VARCHAR(255) NOT NULL UNIQUE
);

-- ============================================================
-- Catalog table: task_status
-- ============================================================
CREATE TABLE task_status (
    status        VARCHAR(50) PRIMARY KEY,
    display_name  VARCHAR(100) NOT NULL,
    color_hex     CHAR(7) NOT NULL,
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    is_terminal   BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT chk_task_status_color_hex
      CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE INDEX idx_task_status_sort_order ON task_status(sort_order);

-- ============================================================
-- Table: tasks
-- ============================================================
CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,

    status       VARCHAR(50) NOT NULL,  -- FK to task_status(status)

    assigned_to  BIGINT,
    due_date     DATE,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tasks_project
      FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,

    CONSTRAINT fk_tasks_assignee
      FOREIGN KEY (assigned_to) REFERENCES cocoUser(id) ON DELETE SET NULL,

    CONSTRAINT fk_tasks_status
      FOREIGN KEY (status) REFERENCES task_status(status) ON DELETE RESTRICT
);

CREATE INDEX idx_tasks_project_id ON tasks(project_id);
CREATE INDEX idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX idx_tasks_status ON tasks(status);

CREATE TRIGGER trg_tasks_set_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Bridge table: cocoUser_project_role
-- (a user has exactly one role within a project)
-- ============================================================
CREATE TABLE cocoUser_project_role (
    user_id     BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,

    -- Enforces: one role per (user, project)
    PRIMARY KEY (user_id, project_id),

    CONSTRAINT fk_upr_user
      FOREIGN KEY (user_id) REFERENCES cocoUser(id) ON DELETE CASCADE,

    CONSTRAINT fk_upr_project
      FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE,

    CONSTRAINT fk_upr_role
      FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);

CREATE INDEX idx_upr_project_id ON cocoUser_project_role(project_id);
CREATE INDEX idx_upr_role_id ON cocoUser_project_role(role_id);
CREATE INDEX idx_upr_user_id ON cocoUser_project_role(user_id);
