-- ============================================================
-- COCO - PostgreSQL
-- ============================================================

DROP DATABASE IF EXISTS "cocoDB";

CREATE DATABASE "cocoDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'es_ES.UTF-8'
    LC_CTYPE = 'es_ES.UTF-8'
    TEMPLATE = template0
    CONNECTION LIMIT = -1;


-- ============================================================
--  Función
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Tablas
-- ============================================================

-- Tabla: usuarios
CREATE TABLE usuarios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    name              VARCHAR(255),
    lastname          VARCHAR(255),
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    profile_photo_url TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_usuarios_set_updated_at
BEFORE UPDATE ON usuarios
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Tabla: proyectos
CREATE TABLE proyectos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL UNIQUE,
    description  TEXT,
    logo_url     TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_proyectos_set_updated_at
BEFORE UPDATE ON proyectos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Tabla: roles
CREATE TABLE roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name  VARCHAR(255) NOT NULL UNIQUE
);


-- Tabla catálogo: tarea_estados
CREATE TABLE tarea_estados (
    status        VARCHAR(50) PRIMARY KEY,
    display_name  VARCHAR(100) NOT NULL,
    color_hex     CHAR(7) NOT NULL,
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    is_terminal   BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT chk_tarea_estados_color_hex
      CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE INDEX idx_tarea_estados_sort_order ON tarea_estados(sort_order);


-- Tabla: tareas
CREATE TABLE tareas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,

    status       VARCHAR(50) NOT NULL,  -- FK a tarea_estados(status)

    assigned_to  BIGINT,
    due_date     DATE,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_tareas_proyecto
      FOREIGN KEY (project_id) REFERENCES proyectos(id) ON DELETE CASCADE,

    CONSTRAINT fk_tareas_usuario_asignado
      FOREIGN KEY (assigned_to) REFERENCES usuarios(id) ON DELETE SET NULL,

    CONSTRAINT fk_tareas_status
      FOREIGN KEY (status) REFERENCES tarea_estados(status) ON DELETE RESTRICT
);

CREATE INDEX idx_tareas_project_id ON tareas(project_id);
CREATE INDEX idx_tareas_assigned_to ON tareas(assigned_to);
CREATE INDEX idx_tareas_status ON tareas(status);

CREATE TRIGGER trg_tareas_set_updated_at
BEFORE UPDATE ON tareas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Tabla puente: usuarios_proyectos_roles (N:M:N)
CREATE TABLE usuarios_proyectos_roles (
    user_id     BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,

    PRIMARY KEY (user_id, project_id, role_id),

    CONSTRAINT fk_upr_usuario
      FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE,

    CONSTRAINT fk_upr_proyecto
      FOREIGN KEY (project_id) REFERENCES proyectos(id) ON DELETE CASCADE,

    CONSTRAINT fk_upr_rol
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_upr_project_id ON usuarios_proyectos_roles(project_id);
CREATE INDEX idx_upr_role_id ON usuarios_proyectos_roles(role_id);
