spring.config.activate.on-profile=local

# --- Datasource (PostgreSQL LOCAL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/coco
spring.datasource.username=coco_user
spring.datasource.password=coco_user
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Logging util en dev ---
logging.level.root=INFO
logging.level.com.coco=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=OFF

# --- JWT dev ---
coco.jwt.secret="LOCAL_DEV_SECRET_5697f540a76563fe42cc39ea2fab24ad61974784bc3230b9753af6785e9af802"
coco.jwt.expiration-seconds=3600

# --- CORS para Angular local ---
coco.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200
