spring.config.activate.on-profile=test

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway ON en integración real  (para validar migraciones)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logging en tests
logging.level.root=WARN
logging.level.com.coco=INFO

# JWT para tests (fijo)
coco.jwt.secret=TEST_SECRET
coco.jwt.expiration-seconds=3600

# CORS
coco.cors.allowed-origins=http://localhost
coco.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
coco.cors.allowed-headers=Authorization,Content-Type
coco.cors.allow-credentials=true
