name: CI - Backend (Spring Boot)

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"
  push:
    branches: [ "dev " ]
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & Test
        run: ./mvnw -B clean test

      # Opcional pero “huele” a senior: verifica que compila el jar final
      - name: Package
        run: ./mvnw -B -DskipTests package
